"""ROM-specific relocation sidecars; reject missing or stale scan metadata."""
import hashlib
from pathlib import Path


HASH_PREFIX = '# ROM SHA-256\t'


def path_for(rom_path):
    return Path(str(rom_path) + '.relocmap.tsv')


def write(rom_path, rom, entries):
    lines = [HASH_PREFIX + hashlib.sha256(rom).hexdigest(),
             '# built address\toriginal loc -- generated by build.py']
    lines.extend('%s\t%s' % entry for entry in entries)
    path_for(rom_path).write_text('\n'.join(lines) + '\n', encoding='utf-8')


def load(rom_path, rom=None):
    path = path_for(rom_path)
    if not path.is_file():
        raise SystemExit('relocmap: missing %s; rebuild this ROM with tools/build.py '
                         'and keep its .relocmap.tsv alongside it' % path)
    lines = path.read_text(encoding='utf-8').splitlines()
    rom = Path(rom_path).read_bytes() if rom is None else rom
    expected = HASH_PREFIX + hashlib.sha256(rom).hexdigest()
    if not lines or lines[0] != expected:
        raise SystemExit('relocmap: ROM hash mismatch in %s; rebuild this ROM with '
                         'tools/build.py to regenerate its map' % path)
    entries = {}
    for line in lines[1:]:
        if not line or line.startswith('#'):
            continue
        fields = line.split('\t')
        if len(fields) != 2:
            raise SystemExit('relocmap: malformed entry in %s: %r' % (path, line))
        built, original = fields
        entries[built] = original
    return entries
